import Foundation
import Network
@preconcurrency import Security
@preconcurrency import CoreFoundation
@preconcurrency import CockerCore

/// TLS-over-TCP wrapper around the Docker API server. Started when the
/// operator sets `COCKER_TCP_TLS_PORT` and provided certs via
/// `cocker daemon tls-init`. The TLS handshake requires both sides to
/// authenticate (mTLS) so any reachable port can't be used by an
/// unauthenticated client.
///
/// Implementation note : we don't speak HTTP/2 ; clients connect over
/// HTTP/1.1 (same protocol the Unix socket uses). The handler reuses
/// `DockerAPIServer.handleRequest` so endpoint coverage is identical —
/// there's no second copy of the routing table to keep in sync.
///
/// Why Network.framework over BSD sockets + SecureTransport :
/// SecureTransport is deprecated since macOS 10.15 ; Network.framework
/// is the supported path forward. The `nw_protocol_options_set_*`
/// C helpers expose enough knobs for mTLS without dragging in NIOSSL.

/// Generic @unchecked Sendable box. Used here to carry SecKey/CFData
/// (neither is Sendable in Apple's headers) into a @Sendable closure
/// that touches them on a single dispatch — the wrap is sound because
/// we never hand the value to another concurrent reader.
private final class UncheckedBox<T>: @unchecked Sendable {
    let value: T
    init(_ value: T) { self.value = value }
}

/// Outcome of one `conn.receive` raced against an idle-timeout sleep.
private enum TLSRecvOutcome {
    case data(Data)
    case eof        // clean close, error, or empty complete
    case timedOut   // no bytes for the idle window
}

@MainActor
final class DockerAPITLSListener {
    private let port: NWEndpoint.Port
    private let tlsDir: URL
    private let dockerAPI: DockerAPIServer
    private let engine: ContainerEngine
    private var listener: NWListener?

    init(port: UInt16, tlsDir: URL, dockerAPI: DockerAPIServer, engine: ContainerEngine) {
        self.port = NWEndpoint.Port(rawValue: port)!
        self.tlsDir = tlsDir
        self.dockerAPI = dockerAPI
        self.engine = engine
    }

    func start() async throws {
        // Load the daemon's PKCS#12 identity — generated by
        // `cocker daemon tls-init`. We import it into the keychain
        // ephemeral, extract the SecIdentity, and hand it to
        // Network.framework's TLS options.
        let p12 = tlsDir.appendingPathComponent("server.p12")
        let p12Data = try Data(contentsOf: p12)
        // Pair file `server.p12.pass` holds the passphrase that
        // `cocker daemon tls-init` chose when wrapping the key. We use
        // a non-empty passphrase because SecPKCS12Import returns
        // errSecAuthFailed (-25293) on an empty-password bundle on
        // current macOS, even when `cocker daemon tls-init` produced
        // it with `-legacy` (RC2/SHA1) framing.
        let passData = (try? Data(contentsOf: tlsDir.appendingPathComponent("server.p12.pass")))
        let passphrase = passData.flatMap { String(data: $0, encoding: .utf8) } ?? ""
        var importItems: CFArray?
        let importOptions: [String: Any] = [
            kSecImportExportPassphrase as String: passphrase as CFString
        ]
        let importStatus = SecPKCS12Import(p12Data as CFData, importOptions as CFDictionary, &importItems)
        guard importStatus == errSecSuccess,
              let items = importItems as? [[String: Any]],
              let firstItem = items.first,
              let identity = firstItem[kSecImportItemIdentity as String]
        else {
            throw CockerError.internalError("server.p12 didn't import (status \(importStatus)) — re-run `cocker daemon tls-init`")
        }
        // The bridge from CFTypeRef → sec_identity_t is via
        // `sec_identity_create` (header : Security.framework's
        // sec_identity.h, available since macOS 10.14).
        let identitySec = identity as! SecIdentity
        guard let secIdentity = sec_identity_create(identitySec) else {
            throw CockerError.internalError("sec_identity_create returned nil")
        }

        // Pre-warm the private key. The first SecKeyCreateSignature on
        // a freshly imported PKCS#12 identity takes 3 to 4 minutes on
        // macOS — keychain ACL bootstrap, slow on un-trusted apps.
        // Subsequent calls return in single-digit milliseconds. If we
        // skip this step the very first TLS handshake times out before
        // boringssl gets its signature back (-9816). Doing it once at
        // startup is the difference between "TLS works" and "TLS hangs
        // for 4 minutes on first request".
        var prewarmKey: SecKey?
        if SecIdentityCopyPrivateKey(identitySec, &prewarmKey) == errSecSuccess,
           let key = prewarmKey {
            CockerLog.shared.info("docker-api-tls", "pre-warming server key (one-time, ~10s; up to 4 min on cold keychain)…")
            let t = Date()
            // Run synchronously on a background queue and wait — the
            // TLS listener must not accept connections before the
            // first SecKeyCreateSignature call has primed the
            // keychain ACL machinery, otherwise the first incoming
            // handshake takes the slow path and exceeds the client's
            // TLS timeout. After this single call subsequent signs
            // return in milliseconds.
            let scratch = Data(repeating: 0, count: 32) as CFData
            // SecKey + CFData aren't Sendable in their public headers,
            // and SecKeyCreateSignature is thread-safe in practice (we
            // only hold them on this single dispatch). Box them so the
            // @Sendable closure captures the unchecked wrapper instead.
            let boxedKey = UncheckedBox(key)
            let boxedScratch = UncheckedBox(scratch)
            await withCheckedContinuation { (k: CheckedContinuation<Void, Never>) in
                DispatchQueue.global(qos: .userInitiated).async {
                    var err: Unmanaged<CFError>?
                    _ = SecKeyCreateSignature(boxedKey.value, .ecdsaSignatureMessageX962SHA256, boxedScratch.value, &err)
                    k.resume()
                }
            }
            CockerLog.shared.info("docker-api-tls", "server key pre-warmed in \(Int(Date().timeIntervalSince(t)))s")
        }

        let tlsOptions = NWProtocolTLS.Options()
        sec_protocol_options_set_local_identity(tlsOptions.securityProtocolOptions, secIdentity)
        // Force TLS 1.2 minimum. We don't pin the maximum — with an
        // ECDSA cert (mandatory ; see `cocker daemon tls-init`) both
        // TLS 1.2 and 1.3 work. The RSA path is broken on macOS
        // (CSSMERR_CSP_INVALID_KEYATTR_MASK when boringssl calls the
        // legacy CSSM-backed key produced by SecPKCS12Import).
        sec_protocol_options_set_min_tls_protocol_version(
            tlsOptions.securityProtocolOptions, .TLSv12
        )
        // mTLS — require the client to present a cert too. Without
        // this anyone with TCP reach to the port could drive cockerd
        // (= root inside any container). Disabled-by-default in the
        // env-var "COCKER_TCP_TLS_NO_CLIENT_AUTH" to allow operators
        // to test the TLS-only path without rolling client certs.
        let mtlsEnabled = ProcessInfo.processInfo.environment["COCKER_TCP_TLS_NO_CLIENT_AUTH"] == nil
        if mtlsEnabled {
            sec_protocol_options_set_peer_authentication_required(
                tlsOptions.securityProtocolOptions, true
            )
            // Pin the trust anchors to our CA only. Without an explicit
            // verify_block sec_protocol falls back to the system trust
            // store ; that would accept any cert chained to a public CA
            // and defeat the point of having generated our own. The
            // helper closures are kept dead simple — Network.framework's
            // verify-block contract is tricky and a hanging or
            // double-completing closure stalls the entire handshake.
            let caPath = tlsDir.appendingPathComponent("ca.pem")
            let caPem = (try? String(contentsOf: caPath, encoding: .utf8)) ?? ""
            // SecCertificateCreateWithData wants DER bytes (no PEM
            // header / footer). Strip "-----BEGIN ...-----" and
            // base64-decode the body.
            let derBytes: Data = {
                let stripped = caPem
                    .components(separatedBy: "\n")
                    .filter { !$0.hasPrefix("-----") }
                    .joined()
                return Data(base64Encoded: stripped) ?? Data()
            }()
            guard let caCert = derBytes.isEmpty ? nil : SecCertificateCreateWithData(nil, derBytes as CFData) else {
                throw CockerError.internalError("could not parse ca.pem — re-run `cocker daemon tls-init`")
            }
            sec_protocol_options_set_verify_block(
                tlsOptions.securityProtocolOptions,
                { _, secTrust, completion in
                    let trust = sec_trust_copy_ref(secTrust).takeRetainedValue()
                    SecTrustSetAnchorCertificates(trust, [caCert] as CFArray)
                    SecTrustSetAnchorCertificatesOnly(trust, true)
                    // Replace the policy set by the framework (TLS
                    // server) with the TLS client policy — we're
                    // validating a client cert so the EKU check has
                    // to look for `id-kp-clientAuth`. Without this
                    // SecTrustEvaluateWithError reports "certificate
                    // is not permitted for this usage".
                    let policy = SecPolicyCreateSSL(false, nil)
                    SecTrustSetPolicies(trust, policy)
                    var error: CFError?
                    let ok = SecTrustEvaluateWithError(trust, &error)
                    if !ok {
                        CockerLog.shared.warn("docker-api-tls",
                            "client cert rejected: \(error?.localizedDescription ?? "unknown")")
                    }
                    completion(ok)
                },
                DispatchQueue.global(qos: .userInitiated)
            )
        }

        let params = NWParameters(tls: tlsOptions, tcp: .init())
        params.acceptLocalOnly = false
        params.allowLocalEndpointReuse = true

        let l = try NWListener(using: params, on: port)
        listener = l
        l.newConnectionHandler = { [weak self] conn in
            // Snapshot self into a local so the nested Task closure
            // (which is @Sendable) captures the local instead of trying
            // to re-capture the outer var — Swift 6 strict concurrency
            // rejects the latter.
            let strongSelf = self
            conn.stateUpdateHandler = { state in
                switch state {
                case .ready:
                    Task { @MainActor in
                        strongSelf?.handleConnection(conn)
                    }
                case .failed(let err):
                    CockerLog.shared.warn("docker-api-tls", "conn failed: \(err)")
                    conn.cancel()
                default:
                    break
                }
            }
            // Start the connection on a background queue ; main is busy
            // serving IPC.
            conn.start(queue: .global(qos: .userInitiated))
        }
        l.stateUpdateHandler = { state in
            switch state {
            case .ready:
                CockerLog.shared.info("docker-api-tls",
                    "TLS listening on tcp://0.0.0.0:\(self.port.rawValue) — DOCKER_HOST=tcp://<host>:\(self.port.rawValue)")
            case .failed(let err):
                CockerLog.shared.error("docker-api-tls", "listener failed: \(err)")
            default: break
            }
        }
        l.start(queue: .main)
    }

    /// Cancel the NWListener so the OS port is released and in-flight
    /// connection handlers stop accepting new work. Called from main's
    /// graceful-shutdown path before the daemon exits.
    func stop() {
        listener?.cancel()
        listener = nil
        CockerLog.shared.info("docker-api-tls", "TLS listener stopped")
    }

    /// Bridge an accepted TLS NWConnection into the Docker API HTTP
    /// handler.
    ///
    /// Earlier revisions of this method tried to reuse the existing
    /// fd-based `parseHTTPRequest(from: fd)` API by setting up two
    /// `Pipe()` objects to bridge NWConnection ↔ fd. That path turned
    /// out to be brittle — Foundation's `Pipe` aggressively closes its
    /// fds on deinit, the macOS kernel re-uses freed fd numbers
    /// instantly, and we ended up with one pipe's writer end re-bound
    /// to another pipe's read fd, mixing request bytes into the
    /// response stream. So the bridge now keeps the request/response
    /// fully in memory : drain the NWConnection into a `Data` buffer,
    /// parse the headers / body in-process, route the request through
    /// the standard handler, and serialize the response back out on
    /// the same NWConnection. No pipes, no fd lifetime games.
    private func handleConnection(_ conn: NWConnection) {

        // Receive until we have the full HTTP request (headers + body)
        // and then route it via the in-memory bridge.
        Task.detached { [weak self] in
            guard let self else { return }
            var buffer = Data()
            // Loop : keep receiving until headers are complete and the
            // body (if any) is fully drained.
            var headerEnd: Int? = nil
            var contentLength = 0
            // Per-receive IDLE timeout, reset on every chunk. NWConnection.receive
            // has no timeout of its own. A fixed whole-request deadline is wrong
            // twice over : it kills a legitimately long transfer that is still
            // making progress (a large image push over a slow link), and it
            // never fires while the client is actually stalled inside receive()
            // — only between chunks. Racing each receive against a sleep bounds
            // a stalled / slowloris connection without capping honest big bodies.
            let idleTimeoutNanos: UInt64 = 30 * 1_000_000_000
            receiveLoop: while headerEnd == nil || buffer.count < headerEnd! + 4 + contentLength {
                let outcome: TLSRecvOutcome = await withTaskGroup(of: TLSRecvOutcome.self) { group in
                    group.addTask {
                        await withCheckedContinuation { (k: CheckedContinuation<TLSRecvOutcome, Never>) in
                            conn.receive(minimumIncompleteLength: 1, maximumLength: 64 * 1024) { data, _, _, error in
                                if let error {
                                    CockerLog.shared.warn("docker-api-tls", "receive error: \(error)")
                                    k.resume(returning: .eof)
                                    return
                                }
                                if let data, !data.isEmpty {
                                    k.resume(returning: .data(data))
                                } else {
                                    k.resume(returning: .eof)  // isComplete / empty
                                }
                            }
                        }
                    }
                    group.addTask {
                        try? await Task.sleep(nanoseconds: idleTimeoutNanos)
                        return .timedOut
                    }
                    let first = await group.next() ?? .eof
                    // If the idle timer won, cancel the connection NOW so the
                    // still-pending receive callback fires and its child task
                    // can finish — withTaskGroup awaits every child at scope
                    // exit, so a stuck continuation would otherwise hang here.
                    if case .timedOut = first { conn.cancel() }
                    group.cancelAll()
                    return first
                }
                let chunk: Data
                switch outcome {
                case .timedOut:
                    CockerLog.shared.warn("docker-api-tls", "receive idle-timed out")
                    return  // conn already cancelled inside the group
                case .eof:
                    break receiveLoop
                case .data(let d):
                    chunk = d
                }
                buffer.append(chunk)
                // Bound the header section : until we've seen the blank line
                // that ends the headers, refuse to accumulate more than the
                // shared cap. Mirrors the fd parser (which stops at the same
                // 64 KiB) and stops a client from exhausting memory by never
                // terminating the header block. Reachable unauthenticated if
                // COCKER_TCP_TLS_NO_CLIENT_AUTH disables mTLS, so it matters.
                if headerEnd == nil && buffer.count > HTTPLimits.maxHeaderBytes {
                    CockerLog.shared.warn("docker-api-tls", "header section exceeded \(HTTPLimits.maxHeaderBytes) bytes")
                    conn.cancel()
                    return
                }
                // Find header terminator if we don't have it yet.
                if headerEnd == nil {
                    if let r = buffer.range(of: Data([0x0D, 0x0A, 0x0D, 0x0A])) {
                        headerEnd = r.lowerBound
                        // Parse Content-Length from headers.
                        if let head = String(data: buffer.subdata(in: 0..<r.lowerBound), encoding: .utf8) {
                            for line in head.components(separatedBy: "\r\n") {
                                if line.lowercased().hasPrefix("content-length:") {
                                    contentLength = Int(line.dropFirst("content-length:".count).trimmingCharacters(in: .whitespaces)) ?? 0
                                }
                            }
                        }
                        // Refuse oversize bodies before draining gigabytes
                        // into `buffer` (DoS guard, mirrors the fd parser).
                        if contentLength > HTTPLimits.maxBodyBytes {
                            conn.cancel()
                            return
                        }
                    }
                }
            }
            guard let request = self.parseHTTPRequest(from: buffer) else {
                conn.cancel()
                return
            }
            let response = await self.dockerAPI.routeAndSerialize(request)
            // Write response back over the TLS connection in one shot,
            // then close. Use withCheckedContinuation instead of a
            // DispatchSemaphore so we don't block the cooperative thread
            // pool — Swift 6 marks DispatchSemaphore.wait() unavailable
            // from async contexts for exactly that reason.
            await withCheckedContinuation { (cont: CheckedContinuation<Void, Never>) in
                conn.send(content: response, completion: .contentProcessed { err in
                    if let err { CockerLog.shared.warn("docker-api-tls", "send error: \(err)") }
                    cont.resume()
                })
            }
            conn.cancel()
        }
    }

    /// In-memory HTTP/1.1 request parse — used by the TLS bridge so we
    /// don't have to push bytes through a pipe (see `handleConnection`).
    nonisolated private func parseHTTPRequest(from raw: Data) -> HTTPRequest? {
        guard let sep = raw.range(of: Data([0x0D, 0x0A, 0x0D, 0x0A])) else { return nil }
        let headerData = raw.subdata(in: 0..<sep.lowerBound)
        guard let headerStr = String(data: headerData, encoding: .utf8) else { return nil }
        let lines = headerStr.components(separatedBy: "\r\n")
        guard !lines.isEmpty else { return nil }
        let requestParts = lines[0].split(separator: " ", maxSplits: 2).map(String.init)
        guard requestParts.count >= 2 else { return nil }
        let method = requestParts[0]
        let rawPath = requestParts[1]
        var path = rawPath
        var query: [String: String] = [:]
        if let qIdx = rawPath.firstIndex(of: "?") {
            path = String(rawPath[..<qIdx])
            let queryString = String(rawPath[rawPath.index(after: qIdx)...])
            for pair in queryString.split(separator: "&") {
                let kv = pair.split(separator: "=", maxSplits: 1)
                if kv.count == 2 {
                    let k = String(kv[0]).removingPercentEncoding ?? String(kv[0])
                    let v = String(kv[1]).removingPercentEncoding ?? String(kv[1])
                    query[k] = v
                } else if kv.count == 1 {
                    query[String(kv[0])] = ""
                }
            }
        }
        // Strip /v1.NN prefix the way the canonical parser does.
        if path.hasPrefix("/v") {
            let afterV = path.dropFirst(2)
            if let slash = afterV.firstIndex(of: "/") {
                path = String(afterV[slash...])
            }
        }
        var headers: [String: String] = [:]
        for line in lines.dropFirst() {
            let parts = line.split(separator: ":", maxSplits: 1)
            if parts.count == 2 {
                headers[String(parts[0]).lowercased()] = String(parts[1]).trimmingCharacters(in: .whitespaces)
            }
        }
        let body = raw.suffix(from: sep.upperBound)
        return HTTPRequest(method: method, path: path, query: query, headers: headers, body: Data(body))
    }
}
