import Foundation

// Bootstrap files that cockerd writes into a container's rootfs before
// booting the VM. These are read by cocker-init (PID 1) at boot :
//
//   /cocker-spec    — argv + env + workdir, NUL-separated (more robust
//                     than the kernel cmdline which can't carry spaces
//                     or quotes inside parameter values).
//   /etc/resolv.conf — points libc DNS at the in-VM proxy (127.0.0.1)
//                     which forwards over vsock to cockerd.
//   /etc/hosts      — minimal default + the container's own name/hostname.
//
// Extracted from VMRuntime so the file layout and content are unit-
// testable against a temp directory.

public enum RootfsBootstrap {

    // MARK: - /cocker-spec
    //
    // Wire format — length-prefixed binary, version 2. The old NUL-and-newline
    // format broke whenever argv carried a literal newline (`bash -c "a\nb"`
    // would be mis-parsed by cocker-init into argv + env). The new format is :
    //
    //   magic:    "COCKER\x02" (7 bytes — "COCKER" + version byte 0x02)
    //   argc:     u32 BE
    //   for each argv : u32 BE length, then bytes
    //   envc:     u32 BE
    //   for each env entry : u32 BE length, then bytes
    //   wd_len:   u32 BE
    //   wd:       bytes
    //
    // All length fields are unsigned big-endian 32-bit. Strings are UTF-8.
    // Total size is bounded by the kernel cmdline (we don't enforce limits
    // beyond what's reasonable).

    /// Magic header for the v2 spec format. cocker-init's spec_load() reads
    /// these 7 bytes first and refuses to proceed on mismatch.
    public static let specMagic: [UInt8] = Array("COCKER\u{02}".utf8)

    public static func encodeSpec(command: [String],
                                  env: [String: String],
                                  workdir: String?) -> Data {
        var data = Data()
        data.append(contentsOf: specMagic)

        // argv
        data.appendUInt32BE(UInt32(command.count))
        for arg in command {
            let bytes = Array(arg.utf8)
            data.appendUInt32BE(UInt32(bytes.count))
            data.append(contentsOf: bytes)
        }

        // env — inject sensible defaults if user didn't provide them
        var entries: [String] = []
        if env["PATH"] == nil {
            entries.append("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
        }
        if env["HOME"] == nil { entries.append("HOME=/root") }
        if env["TERM"] == nil { entries.append("TERM=xterm") }
        for (k, v) in env { entries.append("\(k)=\(v)") }

        data.appendUInt32BE(UInt32(entries.count))
        for entry in entries {
            let bytes = Array(entry.utf8)
            data.appendUInt32BE(UInt32(bytes.count))
            data.append(contentsOf: bytes)
        }

        // workdir
        let wd = workdir ?? env["WORKDIR"] ?? "/"
        let wdBytes = Array(wd.utf8)
        data.appendUInt32BE(UInt32(wdBytes.count))
        data.append(contentsOf: wdBytes)

        return data
    }

    /// Write the spec atomically into `<rootfs>/cocker-spec`.
    public static func writeSpec(to rootfsPath: URL,
                                 command: [String],
                                 env: [String: String],
                                 workdir: String?) throws {
        let data = encodeSpec(command: command, env: env, workdir: workdir)
        try data.write(to: rootfsPath.appendingPathComponent("cocker-spec"), options: .atomic)
    }

    // MARK: - /etc/resolv.conf

    public static func buildResolvConf(dnsIP: String) -> String {
        """
        # Generated by cockerd
        nameserver \(dnsIP)
        nameserver ::1
        search cocker
        options ndots:1
        options timeout:1
        options attempts:2

        """
    }

    public static func writeResolvConf(to rootfsPath: URL, dnsIP: String) throws {
        let etcDir = rootfsPath.appendingPathComponent("etc")
        try? FileManager.default.createDirectory(at: etcDir, withIntermediateDirectories: true)
        let path = etcDir.appendingPathComponent("resolv.conf")
        try buildResolvConf(dnsIP: dnsIP).write(to: path, atomically: true, encoding: .utf8)
    }

    // MARK: - /etc/hosts

    public static func buildHosts(containerName: String, hostname: String, ip: String?) -> String {
        var hosts = """
        127.0.0.1   localhost
        ::1         localhost

        """
        if let ip {
            hosts += "\(ip)   \(containerName) \(hostname)\n"
        }
        return hosts
    }

    /// Writes /etc/hosts only if it doesn't already exist (to avoid clobbering
    /// the image's own hosts file with extra entries).
    public static func writeHostsIfAbsent(to rootfsPath: URL,
                                          containerName: String,
                                          hostname: String,
                                          ip: String?) throws {
        let etcDir = rootfsPath.appendingPathComponent("etc")
        try? FileManager.default.createDirectory(at: etcDir, withIntermediateDirectories: true)
        let path = etcDir.appendingPathComponent("hosts")
        if FileManager.default.fileExists(atPath: path.path) { return }
        try buildHosts(containerName: containerName, hostname: hostname, ip: ip)
            .write(to: path, atomically: true, encoding: .utf8)
    }
}

extension Data {
    fileprivate mutating func appendUInt32BE(_ value: UInt32) {
        append(UInt8((value >> 24) & 0xFF))
        append(UInt8((value >> 16) & 0xFF))
        append(UInt8((value >>  8) & 0xFF))
        append(UInt8( value        & 0xFF))
    }
}

