import Foundation

// Bootstrap files that cockerd writes into a container's rootfs before
// booting the VM. These are read by cocker-init (PID 1) at boot :
//
//   /cocker-spec    — argv + env + workdir, NUL-separated (more robust
//                     than the kernel cmdline which can't carry spaces
//                     or quotes inside parameter values).
//   /etc/resolv.conf — points libc DNS at the in-VM proxy (127.0.0.1)
//                     which forwards over vsock to cockerd.
//   /etc/hosts      — minimal default + the container's own name/hostname.
//
// Extracted from VMRuntime so the file layout and content are unit-
// testable against a temp directory.

public enum RootfsBootstrap {

    // MARK: - /cocker-spec

    /// Encode the container spec into the wire format cocker-init reads.
    /// Three NUL-separated lines, each terminated by \n :
    ///   argv0\0argv1\0...\n
    ///   env0\0env1\0...\n
    ///   workdir\n
    public static func encodeSpec(command: [String],
                                  env: [String: String],
                                  workdir: String?) -> Data {
        var data = Data()

        // argv
        for (i, arg) in command.enumerated() {
            if i > 0 { data.append(0) }
            data.append(arg.data(using: .utf8) ?? Data())
        }
        data.append(0x0A)

        // env — inject sensible defaults if user didn't provide them
        var entries: [String] = []
        if env["PATH"] == nil {
            entries.append("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
        }
        if env["HOME"] == nil { entries.append("HOME=/root") }
        if env["TERM"] == nil { entries.append("TERM=xterm") }
        for (k, v) in env { entries.append("\(k)=\(v)") }

        for (i, entry) in entries.enumerated() {
            if i > 0 { data.append(0) }
            data.append(entry.data(using: .utf8) ?? Data())
        }
        data.append(0x0A)

        // workdir — fall back to env["WORKDIR"] for backwards compat with
        // older callers, then "/" if neither is set.
        let wd = workdir ?? env["WORKDIR"] ?? "/"
        data.append(wd.data(using: .utf8) ?? Data())
        data.append(0x0A)

        return data
    }

    /// Write the spec atomically into `<rootfs>/cocker-spec`.
    public static func writeSpec(to rootfsPath: URL,
                                 command: [String],
                                 env: [String: String],
                                 workdir: String?) throws {
        let data = encodeSpec(command: command, env: env, workdir: workdir)
        try data.write(to: rootfsPath.appendingPathComponent("cocker-spec"), options: .atomic)
    }

    // MARK: - /etc/resolv.conf

    public static func buildResolvConf(dnsIP: String) -> String {
        """
        # Generated by cockerd
        nameserver \(dnsIP)
        nameserver ::1
        search cocker
        options ndots:1
        options timeout:1
        options attempts:2

        """
    }

    public static func writeResolvConf(to rootfsPath: URL, dnsIP: String) throws {
        let etcDir = rootfsPath.appendingPathComponent("etc")
        try? FileManager.default.createDirectory(at: etcDir, withIntermediateDirectories: true)
        let path = etcDir.appendingPathComponent("resolv.conf")
        try buildResolvConf(dnsIP: dnsIP).write(to: path, atomically: true, encoding: .utf8)
    }

    // MARK: - /etc/hosts

    public static func buildHosts(containerName: String, hostname: String, ip: String?) -> String {
        var hosts = """
        127.0.0.1   localhost
        ::1         localhost

        """
        if let ip {
            hosts += "\(ip)   \(containerName) \(hostname)\n"
        }
        return hosts
    }

    /// Writes /etc/hosts only if it doesn't already exist (to avoid clobbering
    /// the image's own hosts file with extra entries).
    public static func writeHostsIfAbsent(to rootfsPath: URL,
                                          containerName: String,
                                          hostname: String,
                                          ip: String?) throws {
        let etcDir = rootfsPath.appendingPathComponent("etc")
        try? FileManager.default.createDirectory(at: etcDir, withIntermediateDirectories: true)
        let path = etcDir.appendingPathComponent("hosts")
        if FileManager.default.fileExists(atPath: path.path) { return }
        try buildHosts(containerName: containerName, hostname: hostname, ip: ip)
            .write(to: path, atomically: true, encoding: .utf8)
    }
}
