/*
 * cocker-init — minimal Linux init (PID 1) for cocker containers.
 *
 * Boot sequence :
 *   1.  Mount /proc, /sys, /dev as virtual filesystems
 *   2.  Read /proc/cmdline to get cocker.* params from cockerd
 *   3.  Set the hostname
 *   4.  Mount the virtiofs share "root" as the rootfs and switch_root into it
 *   5.  Mount additional volume virtiofs shares (vol0, vol1, …) at the paths
 *       passed via cocker.vol* cmdline params
 *   6.  Bring up lo + eth0 (DHCP) + eth1 (cocker switch fabric, static)
 *   7.  Spawn the in-VM DNS proxy (vsock to cockerd)
 *   8.  Pin /etc/resolv.conf to 127.0.0.1 so libc uses our proxy
 *   9.  Read /cocker-spec and exec the container's command
 *  10.  fork+wait pattern so PID 1 stays alive (prevents kernel panic)
 *  11.  When the container exits, reboot(RB_POWER_OFF)
 *
 * Cross-compile from macOS :
 *   zig cc -target aarch64-linux-musl -static -O2 -o cocker-init \
 *          init.c cmdline.c net.c dns_proxy.c spec.c
 *
 * The output is then packaged into an initrd cpio archive.
 */

#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/reboot.h>
#include "cocker_init.h"

/* Mount the virtiofs rootfs tag "root" at /newroot, then switch_root */
static void switch_to_virtiofs(void) {
    if (mkdir("/newroot", 0755) < 0 && errno != EEXIST)
        die("mkdir /newroot: %s", strerror(errno));

    if (mount("root", "/newroot", "virtiofs", 0, NULL) < 0)
        die("mount virtiofs /newroot: %s", strerror(errno));

    info("virtiofs rootfs mounted at /newroot");

    mkdir("/newroot/proc", 0755);
    mkdir("/newroot/sys", 0755);
    mkdir("/newroot/dev", 0755);
    mkdir("/newroot/run", 0755);
    mkdir("/newroot/tmp", 0755);

    mount("/proc", "/newroot/proc", NULL, MS_MOVE, NULL);
    mount("/sys",  "/newroot/sys",  NULL, MS_MOVE, NULL);
    mount("/dev",  "/newroot/dev",  NULL, MS_MOVE, NULL);

    mount("tmpfs", "/newroot/run", "tmpfs", MS_NOSUID | MS_NODEV,
          "mode=755,size=64m");
    mount("tmpfs", "/newroot/tmp", "tmpfs", MS_NOSUID | MS_NODEV,
          "mode=1777,size=64m");

    if (chdir("/newroot") < 0) die("chdir /newroot: %s", strerror(errno));
    if (mount("/newroot", "/", NULL, MS_MOVE, NULL) < 0)
        die("move /newroot to /: %s", strerror(errno));
    if (chroot(".") < 0) die("chroot: %s", strerror(errno));
    if (chdir("/") < 0) die("chdir /: %s", strerror(errno));
}

/* Mount the per-container volume virtiofs shares (vol0, vol1, …) at the
 * paths specified on the kernel cmdline via cocker.vol<N>=tag:/path. */
static void mount_volumes(const char *cmdline) {
    for (int i = 0; i < 32; i++) {
        char key[16];
        snprintf(key, sizeof(key), "vol%d", i);
        char *spec = cmdline_get(cmdline, key);
        if (!spec) break;

        char *colon = strchr(spec, ':');
        if (!colon) { free(spec); continue; }
        *colon = '\0';
        const char *tag = spec;
        const char *path = colon + 1;

        /* mkdir -p */
        char tmp[512];
        snprintf(tmp, sizeof(tmp), "%s", path);
        for (char *p = tmp + 1; *p; p++) {
            if (*p == '/') { *p = '\0'; mkdir(tmp, 0755); *p = '/'; }
        }
        mkdir(tmp, 0755);

        if (mount(tag, path, "virtiofs", 0, NULL) < 0)
            info("mount %s -> %s failed: %s", tag, path, strerror(errno));
        else
            info("mounted volume %s at %s", tag, path);
        free(spec);
    }
}

/* Write /etc/resolv.conf pointing at the in-VM DNS proxy. udhcpc clobbers
 * this file with the vmnet gateway DNS, so we rewrite it AFTER DHCP runs. */
static void pin_resolv_conf(unsigned int vsock_port) {
    int fd = open("/etc/resolv.conf", O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) return;
    const char *rc =
        "# generated by cocker-init (post-DHCP)\n"
        "nameserver 127.0.0.1\n"
        "search cocker\n"
        "options ndots:0 timeout:1 attempts:2\n";
    write(fd, rc, strlen(rc));
    close(fd);
    info("pinned /etc/resolv.conf to 127.0.0.1 (proxy → vsock CID=2 port=%u)",
         vsock_port);
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;

    /* Bring up initial /proc, /sys, /dev before reading cmdline. */
    mkdir("/proc", 0755);
    mkdir("/sys",  0755);
    mkdir("/dev",  0755);

    if (mount("proc",     "/proc", "proc",     0, NULL) < 0)
        die("mount /proc: %s", strerror(errno));
    if (mount("sysfs",    "/sys",  "sysfs",    0, NULL) < 0)
        die("mount /sys: %s", strerror(errno));
    if (mount("devtmpfs", "/dev",  "devtmpfs", 0, NULL) < 0)
        info("mount /dev: %s (continuing)", strerror(errno));

    char cmdline[4096];
    if (read_cmdline(cmdline, sizeof(cmdline)) < 0)
        die("read /proc/cmdline: %s", strerror(errno));

    info("booted from kernel cmdline");

    char *cid  = cmdline_get(cmdline, "id");
    char *name = cmdline_get(cmdline, "name");
    info("container id=%s name=%s", cid ? cid : "?", name ? name : "?");

    char *hostname = cmdline_get(cmdline, "hostname");
    if (hostname) {
        sethostname(hostname, strlen(hostname));
        info("hostname=%s", hostname);
        free(hostname);
    } else if (name) {
        sethostname(name, strlen(name));
    }

    switch_to_virtiofs();
    mount_volumes(cmdline);

    /* Networking. */
    net_bring_up_loopback();
    net_setup_eth0_dhcp();

    /* DNS proxy first (so resolv.conf pin makes sense). */
    {
        char *vsock_port_s = cmdline_get(cmdline, "dns_vsock_port");
        unsigned int vsock_port = vsock_port_s ? (unsigned int)atoi(vsock_port_s) : 5353;
        if (vsock_port == 0) vsock_port = 5353;
        dns_proxy_spawn(vsock_port);
        pin_resolv_conf(vsock_port);
        if (vsock_port_s) free(vsock_port_s);
    }

    net_setup_eth1_static(cmdline);

    /* Load the container spec (argv + env + workdir). */
    char *child_argv[128];
    int argc_count = spec_load(child_argv, 128);
    if (argc_count == 0 || child_argv[0] == NULL)
        die("empty command in /cocker-spec");

    info("exec: %s (argc=%d)", child_argv[0], argc_count);

    /* Fork + wait : keep PID 1 alive so the kernel doesn't panic when the
     * container's command exits. */
    pid_t child = fork();
    if (child < 0) die("fork: %s", strerror(errno));

    if (child == 0) {
        execvp(child_argv[0], child_argv);
        fprintf(stderr, "[cocker-init] execvp %s: %s\n",
                child_argv[0], strerror(errno));
        _exit(127);
    }

    int status = 0;
    for (;;) {
        pid_t r = waitpid(-1, &status, 0);
        if (r < 0) {
            if (errno == EINTR) continue;
            if (errno == ECHILD) break;
            die("waitpid: %s", strerror(errno));
        }
        if (r == child) break;
    }

    int exitcode = 0;
    if (WIFEXITED(status))         exitcode = WEXITSTATUS(status);
    else if (WIFSIGNALED(status))  exitcode = 128 + WTERMSIG(status);

    info("container exited with code %d", exitcode);

    sync();
    reboot(RB_POWER_OFF);
    _exit(exitcode);
}
